# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 15:02
from __future__ import unicode_literals

from django.db import migrations
import macaddress.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='mac_address',
            field=macaddress.fields.MACAddressField(blank=True, integer=False, max_length=17),
        ),
    ]
