# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0004_auto_20160223_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='mac_address',
            field=models.CharField(max_length=200),
        ),
    ]
